version: '3.3'

services:


  ontology:
    image: leia/ontology:latest  


  ontosem:
    image: leia/ontosem:1.1.1
    environment:
      - SMALLSEM_LEXICON_LOCATION=SmallSem/data/robot_lexicon.py
      - SMALLSEM_RESOURCES_LOCATION=SmallSem/data/nn_static_resources_robot.json

  agents:
    image: leia/agents:latest.yale
    container_name: agents
    ports:
      - 5002:5002
    networks:
      - leia
    command:
      - "python3.6"
      - "-m"
      - "backend.main"
      - "host=0.0.0.0"
      - "port=5002"
    environment:
      - ONTOSEM_HOST=ontosem
      - ONTOSEM_PORT=5001
      - MONGO_PORT=27017
      - ONTOLOGY_HOST=ontology
      - ONTOLOGY_DATABASE=leia-ontology
      - ONTOLOGY_COLLECTION=robot-v.1.0.0

networks:
  leia:
    driver: bridge
