# This compose file is designed to run the all of the static knowledge services and supporting services.
# It will set up a private network, attach the following:
  # 1) A MongoDB service on port 27017
  # 2) An Ontology service on port 5003
  # 3) A Lexicon service on port 5004
# It will set up several shared volumes for archiving the static knowledge.
# It will run initialization containers for each static knowledge service to verify that at least the baseline
# canonical archive is installed and selected.
# This file grants write access to the AWS bucket for publishing knowledge archives.

version: '3.3'

services:

  mongod:
    image: mongo:3.6
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - leia
    command:
      - "mongod"
    volumes:
      - mongodbdata:/data/db

  initialize-lexicon:
    image: leia/lexicon:latest
    networks:
      - leia
    command:
      - "python"
      - "-m"
      - "initialize"
    environment:
      - ARCHIVE_PATH=/app/archives
      - LEXICON_ACTIVE=canonical-v.1.0.0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - lexicon-archives:/app/archives
    depends_on:
      - mongod

  initialize-ontology:
    image: leia/ontology:latest
    networks:
      - leia
    command:
      - "python"
      - "-m"
      - "initialize"
    environment:
      - ARCHIVE_PATH=/app/archives
      - ONTOLOGY_ACTIVE=canonical-v.1.0.0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ontology-archives:/app/archives
    depends_on:
      - mongod

  lexicon:
    image: leia/lexicon:latest
    container_name: lexicon
    ports:
      - 5004:5004
    networks:
      - leia
    command:
      - "python"
      - "-m"
      - "service"
    environment:
      - ARCHIVE_PATH=/app/archives
      - LEXICON_ACTIVE=canonical-v.1.0.0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - AWS_ACCESS_KEY_ID=AKIAI6QCM2FZDSX3PPKQ
      - AWS_SECRET_ACCESS_KEY=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
    volumes:
      - lexicon-archives:/app/archives
    depends_on:
      - initialize-lexicon

  ontology:
    image: leia/ontology:latest
    container_name: ontology
    ports:
      - 5003:8080
    networks:
      - leia
    command:
      - "python"
      - "-m"
      - "Index"
    environment:
      - ARCHIVE_PATH=/app/archives
      - ONTOLOGY_ACTIVE=canonical-v.1.0.0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - AWS_ACCESS_KEY_ID=AKIAI6QCM2FZDSX3PPKQ
      - AWS_SECRET_ACCESS_KEY=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
    volumes:
      - ontology-archives:/app/archives
    depends_on:
      - initialize-ontology

volumes:
  lexicon-archives:
  ontology-archives:
  mongodbdata:

networks:
  leia:
    driver: bridge